# Generated by Django 2.0.3 on 2019-11-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareMarket',
            fields=[
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Open', models.FloatField(max_length=10)),
                ('High', models.FloatField(max_length=10)),
                ('Low', models.FloatField(max_length=10)),
                ('Close', models.FloatField(max_length=10)),
                ('Shares_Traded', models.IntegerField(max_length=5)),
                ('Turnover_Cr', models.FloatField(max_length=10)),
            ],
        ),
    ]
