# Generated by Django 2.0.3 on 2019-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawrkz', '0002_auto_20191120_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemarket',
            name='Shares_Traded',
            field=models.IntegerField(),
        ),
    ]
